ktor {
    application {
        modules = [ com.sashaflake.ApplicationKt.module ]
    }
    deployment {
        port = 8080
    }
}

storage {
    backend = "memory"
    backend = ${?STORAGE_BACKEND}
    dragonfly {
        host = "localhost"
        host = ${?DRAGONFLY_HOST}
        port = "6379"
        port = ${?DRAGONFLY_PORT}
    }
}

jwt {
    secret = "change-me-in-production"
    issuer = "engineer-challenge"
    audience = "engineer-challenge-users"
    expirationMs = 86400000
}
cors {
    allowedHosts = "http://localhost:3000"
    allowedHosts = ${?CORS_ALLOWED_HOSTS}
}
